name: [PRD] 遊戲內容製作需求
description: 企劃部門向技術部門提出的內容製作要求
title: "[PRD] "
labels: ["plan"]

body:
  - type: markdown
    attributes:
      value: |
        請將抽象的企劃概念轉為具體需要實作的事項後，詳細解釋這個製作需求。

        請盡量回答以下問題：
        - 這是一個什麼樣的系統？
        - 玩家會做什麼？
        - 系統會發生什麼事？
        - 系統有哪些組成？
        - 需要哪些資料？
        - 本次實作包含哪些內容？

  - type: textarea
    id: summary
    attributes:
      label: 系統簡述
      description: 用幾句話描述這個系統
      placeholder: |
        例如：
        玩家可以在水域釣魚獲得魚類，
        部分魚可以用於養殖與料理。

    validations:
      required: true

  - type: textarea
    id: player_loop
    attributes:
      label: 玩家流程
      description: 玩家如何與這個系統互動
      placeholder: |
        玩家在水域中進行釣魚，並且經過一定時間的等待後，水面上會浮現水滴粒子效果。
        當水滴與釣竿重合時，玩家需要在 1000 ms 內交互，即可從魚類圖鑑中，依照機率獲得一隻魚。

  - type: textarea
    id: mechanics
    attributes:
      label: 系統規則
      description: 主要玩法與邏輯
      placeholder: |
        請提供詳細的敘述，越詳細越好。

  - type: textarea
    id: systems
    attributes:
      label: 系統組成
      description: 這個功能包含哪些小系統
      placeholder: |
        例如：
        - 釣魚動畫
        - 隨機魚種
        - 條件魚種
        - 釣竿升級
        - 釣竿屬性

  - type: textarea
    id: data_requirements
    attributes:
      label: 需要的資料
      description: 系統需要哪些資料表或內容
      placeholder: |
        例如：
        - 魚種列表
        - 水域列表
        - 掉落機率
        - 釣竿屬性

  - type: textarea
    id: balancing
    attributes:
      label: 數值與機率
      description: 掉落率、機率、限制等
      placeholder: |
        例如：
        iron fish 60%
        silver fish 30%
        golden fish 10%

  - type: textarea
    id: interactions
    attributes:
      label: 與其他系統互動
      description: 是否會影響其他系統
      placeholder: |
        例如：
        - 料理系統
        - 養殖系統
        - 經濟系統

  - type: textarea
    id: scope
    attributes:
      label: 本次實作範圍
      description: 這個 Issue 要完成哪些部分
      placeholder: |
        例如：
        - 基礎釣魚
        - 魚種生成
        - 掉落機率

  - type: textarea
    id: future
    attributes:
      label: 未來擴展
      description: 未來可能加入的功能
      placeholder: |
        例如：
        - 魚類養殖
        - 稀有魚寵物
        - 特殊魚種

  - type: textarea
    id: references
    attributes:
      label: 參考資料
      description: 企劃文件或設計稿